" vim-plug

call plug#begin('~/.vim/plugged')
Plug 'linc01/auto-pairs'
Plug 'fnune/base16-vim'
Plug 'neoclide/coc.nvim'
Plug 'junegunn/fzf.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'itchyny/lightline.vim'
Plug 'elixir-editors/vim-elixir'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'yuezk/vim-js'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
call plug#end()

" VARIABLES
let g:gitgutter_override_sign_column_highlight=0
let g:gitgutter_map_keys=0
let g:lightline = {
  \ 'colorscheme': 'ayu_custom',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'cocstatus', 'gitbranch', 'readonly', 'filename', 'modified' ] ]
  \ },
  \ 'tabline': {
  \   'left': [ ['buffers'] ]
  \ },
  \ 'component_expand': {
  \   'buffers': 'lightline#bufferline#buffers'
  \ },
  \ 'component_type': {
  \   'buffers': 'tabsel'
  \ },
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead',
  \   'cocstatus': 'coc#status'
  \ },
\ }

if !exists("g:syntax_on")
  syntax enable
endif

" THEMING
colorscheme base16-default-dark
hi Normal guibg=NONE ctermbg=NONE

hi Special ctermbg=none
hi NonText ctermbg=none
hi LineNr ctermbg=none ctermfg=240
hi CursorLineNr ctermbg=233 ctermfg=254
hi CursorLine cterm=none ctermbg=233
hi SignColumn ctermbg=none
hi Folded ctermbg=none cterm=none
hi Comment cterm=ITALIC ctermfg=240
hi ErrorMsg cterm=none ctermbg=0
hi StatusLine ctermbg=0 cterm=none
hi StatusLineNC ctermbg=0 cterm=none
hi MatchParen ctermbg=cyan ctermfg=black
hi SpecialKey ctermfg=240
hi Visual ctermbg=235
hi Pmenu ctermbg=232 ctermfg=240
hi PmenuSel ctermbg=235 ctermfg=7
hi GitGutter ctermbg=none

" SETTINGS
filetype indent on
filetype plugin on

set laststatus=2
set showtabline=2
set encoding=utf-8
set nocompatible
set relativenumber nu cursorline
set ts=2 sw=2 sts=2 expandtab autoindent smartindent
set foldmethod=manual nofoldenable
set autoread
set list lcs=trail:·,tab:\|\ 
set incsearch
set hidden
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set updatetime=100
set directory=$HOME/.vim/swp
set rtp+=~/.fzf
set noshowmode
set wrap linebreak
set backspace=indent,eol,start


" Return to the same line you left off at
augroup line_return
  au!
  au BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \ execute 'normal! g`"zvzz' |
    \ endif
augroup END

" KEYBINDINGS
let mapleader=" "

nmap <C-p> :GFiles<CR>

nmap j gj
nmap k gk

nmap <leader>s :%s/\<<C-r><C-w>\>/
nmap <leader>w :w<CR>
nmap <leader>q :q<CR>
nmap <leader>Q :q!<CR>
nmap <leader>p :Files<CR>
nmap <leader>o :ls<CR>:b<Space>
nmap <leader>v :vsplit<CR>
nmap <leader>n :split<CR>
nmap <leader><Del> :bdel<CR>
nmap <leader>h :bprev<CR>
nmap <leader>l :bnext<CR>
nmap <leader>b :buffers<CR>:buffer<Space>

nmap <leader>dd :r !date \+\%Y-\%m-\%d\ \%T<CR>

nmap <leader>ggu :GitGutterUndoHunk<CR>
nmap <leader>gs :G<CR>
