source ~/.dotfiles.loc

export CONFIG="$DOTFILES/config"
export SCRIPTS="$DOTFILES/shell_scripts"
export fpath=( "$CONFIG/zsh/zfunctions" $fpath)
export EDITOR="vim"
export HISTFILE="$HOME/.zhistory"
export SAVEHIST=2000
export HISTSIZE=1000

echoerr() {
  echo $* >&2
}
