[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# VARIABLES
export dotfiles="$HOME/backupity/.dotfiles"
export shell_scripts="$dotfiles/shell_scripts"
export zsh_config="$dotfiles/config/zsh"
export fpath=( "$zsh_config/zfunctions" $fpath)
export EDITOR="vim"
HISTFILE="$HOME/.zhistory"
SAVEHIST=2000
HISTSIZE=1000
zkbd="$zsh_config/zkbd"

bindkey -e # to set keymapping to emacs regardless of EDITOR

[[ -f $zkbd ]] && source $zkbd # custom key mapping

# PROMPT
autoload -U promptinit; promptinit
prompt pure
PURE_GIT_DOWN_ARROW='↓'
PURE_GIT_DOWN_ARROW='↑'
PROMPT='%(?.%F{white}.%F{red})${PURE_PROMPT_SYMBOL:-→}%f '
# PROMPT=$'\n'"%B%F{81}%d%f"$'\n'">%b "

# OPTIONS
setopt histignorealldups sharehistory
setopt correct

# MODULES
autoload -Uz compinit; compinit -D
