[[ -z $DISPLAY && $XDG_VTNR -eq 1 && $USERNAME != "root" ]] && exec startx

# VARIABLES
zkbd="$CONFIG/zsh/zkbd"

[[ -f $zkbd ]] && source $zkbd # custom key mapping

# PROMPT
# PROMPT=$'\n'"%B%F{81}%d%f"$'\n'">%b "
autoload -U promptinit; promptinit
prompt pure
PURE_GIT_DOWN_ARROW='↓'
PURE_GIT_UP_ARROW='↑'
VIM_PROMPT="●"
PROMPT='%(?.%F{white}.%F{red})${VIM_PROMPT}%f '

prompt_pure_update_vim_prompt() {
  zle || {
    print "error: pure_update_vim_prompt must be called when zle is active"
    return 1
  }
  VIM_PROMPT=${${KEYMAP/vicmd/○}/(main|viins)/●}
  zle reset-prompt
}

function zle-line-init zle-keymap-select {
  prompt_pure_update_vim_prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

export KEYTIMEOUT=1

# OPTIONS
setopt histignorealldups sharehistory
setopt correct
setopt autonamedirs
setopt interactivecomments
setopt PROMPT_CR PROMPT_SP
export PROMPT_EOL_MARK="↵"


# MODULES
autoload -Uz compinit; compinit -D
